### ISSUE TITLE
device tree error

### ISSUE THREAD

**Issue by snathicktechno** [sifive/freedom-u540-c000-bootloader#16]
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
can i know what the error is

**Comment by tmagik** [comment]
Please paste the full output of 'make' that produces this error, along with the environment you are running in.

**Comment by snathicktechno** [comment]
Environment size: 182/1020 bytes
RISC-V # 
baudrate=115200
bootdelay=3
bootfile=bbl.bin
ethact=gmac0
ethaddr=70:b3:d5:92:f0:00
fdtcontroladdr=fffde200
ip_dyn=yes
serverip=10.60.132.52
stderr=serial
stdin=serial
stdout=serial

Environment size: 182/1020 bytes
RISC-V # iminfo

## Checking Image at 80000000 ...
Unknown image format!
RISC-V # 
RISC-V # 
RISC-V # setenv ipaddr 192.168.27.2
RISC-V # setenv serverip 192.168.27.1
RISC-V # 
  base bdinfo boot bootd bootefi bootelf bootm bootp bootvx cmp coninfo cp
  crc32 dhcp echo editenv env erase ...
RISC-V # tftpboot 0x80000000 fitimage
gmac0: PHY present at 0
gmac0: Starting autonegotiation...
gmac0: Autonegotiation complete
gmac0: link up, 1000Mbps full-duplex (lpa: 0x6800)
Using gmac0 device
TFTP from server 192.168.27.1; our IP address is 192.168.27.2
Filename 'fitimage'.
Load address: 0x80000000
Loading: *
TFTP error: 'File not found' (1)
Not retrying...
RISC-V # tftpboot 0x80000000 fitImage
gmac0: PHY present at 0
gmac0: Starting autonegotiation...
gmac0: Autonegotiation complete
gmac0: link up, 1000Mbps full-duplex (lpa: 0x2800)
Using gmac0 device
TFTP from server 192.168.27.1; our IP address is 192.168.27.2
Filename 'fitImage'.
Load address: 0x80000000
Loading: #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         ##############################
         499 KiB/s
done
Bytes transferred = 11134698 (a9e6ea hex)
RISC-V # bootm 0x80000000 - 0x80200000
## Loading kernel from FIT Image at 80000000 ...
   Using 'config@1' configuration
   Verifying Hash Integrity ... OK
   Trying 'linux_kernel@1' kernel subimage
     Description:  vmlinux
     Type:         Kernel Image
     Compression:  uncompressed
     Data Start:   0x800000d4
     Data Size:    11116696 Bytes = 10.6 MiB
     Architecture: RISC-V
     OS:           Linux
     Load Address: 0x80200000
     Entry Point:  0x80200000
     Hash algo:    sha256
     Hash value:   c3548a7b357a003279c7a07d56955530812da7324183218f477f5f52f08edcd1
   Verifying Hash Integrity ... sha256+ OK
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree

Thank You for the quick response Troy Benjegerdes

**Comment by tmagik** [comment]
If you are running U-boot, please build/boot the version in https://github.com/tmagik/freedom-u-sdk, which has scripting to build a FIT image. This is probably an easier place to start than using the legacy bootloader, as there is no good way to specify a device tree with the old bootloader.

If you want to try the work-in-progress development U-boot, check out https://github.com/sifive/u-boot, although this is not stable and under heavy development right now.
